require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/posts", type: :request do
  let(:category) { create(:category) }
  let(:valid_attributes) { attributes_for :post, category_id: category.id }
  let(:invalid_attributes) { attributes_for :post, title: nil }

  describe "POST /create" do
    context "when not logged" do
      it "redirect to login page" do
        post posts_url, :params => { :post => valid_attributes }
        expect(response).to redirect_to(new_user_session_url)
      end
      it "doesn't create the post" do
        post posts_url, :params => { :post => valid_attributes }
        expect(Post.last).to be(nil)
      end
    end

    context "when user logged in" do
      let(:current_user) { create :user }
      before { sign_in current_user }

      context "with valid attributes" do
        it "create the post" do
          post posts_url, :params => { :post => valid_attributes }
          expect(Post.last.attributes).to include(valid_attributes.stringify_keys)
        end
        it "redirect to post page" do
          post posts_url, :params => { :post => valid_attributes }
          expect(response).to redirect_to(post_url(Post.last))
        end
      end

      context "with invalid attributes" do
        it "shouldn't create post" do
          post posts_url, :params => { :post => invalid_attributes }
          expect(Post.last).to be(nil)
        end
      end

      it "renders the validation errors" do
        post posts_url, :params => { :post => invalid_attributes }
        expect(response.body).to include(CGI.escape_html(I18n.t("errors.messages.blank")))
      end
    end

  end

  describe "PATCH /update" do
    context "when not logged" do
      it "redirect to login page" do
        post = create(:post)
        patch post_url(post), params: { post: valid_attributes }
        expect(response).to redirect_to(new_user_session_url)
      end
      it "doesn't update the post" do
        post = create(:post)
        patch post_url(post), params: { post: valid_attributes }
        expect(post.attributes).to eq(Post.find(post.id).attributes)
      end
    end

    context "when logged in" do
      let(:current_user) { create :user }
      before { sign_in current_user }

      context "when not authorized" do
        it "redirects to 403" do
          # TODO implement pundit policies
        end
        it "doesn't update the post" do
          # TODO implement pundit policies
        end
      end

      context "when the post is not found" do
        it "renders 404" do
          post_id = 1
          expect { patch post_url(post_id), params: { post: valid_attributes } }.to raise_error(ActiveRecord::RecordNotFound)
        end
      end

      context "with valid attributes" do
        it "updates the post" do
          post = create(:post)
          patch post_url(post), params: { post: valid_attributes }
          expect(Post.find(post.id).attributes).to include(valid_attributes.stringify_keys)
        end
        it "redirects to the post page" do
          post = create(:post)
          patch post_url(post), params: { post: valid_attributes }
          expect(response).to redirect_to(post_url(post))
        end
      end

      context "with invalid attributes" do
        it "doesn't updates the post" do
          post = create(:post)
          patch post_url(post), params: { post: invalid_attributes }
          expect(Post.find(post.id).attributes).to_not include(valid_attributes.stringify_keys)
        end
        it "renders the validation errors" do
          post = create(:post)
          patch post_url(post), params: { post: invalid_attributes }
          expect(response.body).to include(CGI.escape_html(I18n.t("errors.messages.blank")))
        end
      end
    end
  end
end